//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordbookImpressApp.Resx {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordbookImpressApp.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AlertCancel {
            get {
                return ResourceManager.GetString("AlertCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AlertConfirmed {
            get {
                return ResourceManager.GetString("AlertConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AlertCustom {
            get {
                return ResourceManager.GetString("AlertCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AlertNo {
            get {
                return ResourceManager.GetString("AlertNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AlertYes {
            get {
                return ResourceManager.GetString("AlertYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MMM に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CalendarMonthFormat {
            get {
                return ResourceManager.GetString("CalendarMonthFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Available for hire! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeveloperProfileAvailableForHire {
            get {
                return ResourceManager.GetString("DeveloperProfileAvailableForHire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeveloperProfileBio {
            get {
                return ResourceManager.GetString("DeveloperProfileBio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Books に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeveloperProfileBooks {
            get {
                return ResourceManager.GetString("DeveloperProfileBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contact に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeveloperProfileContact {
            get {
                return ResourceManager.GetString("DeveloperProfileContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Donation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeveloperProfileDonationTitle {
            get {
                return ResourceManager.GetString("DeveloperProfileDonationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Followers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeveloperProfileHeaderFollowers {
            get {
                return ResourceManager.GetString("DeveloperProfileHeaderFollowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Twitter
        ///Followers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeveloperProfileHeaderFollowersTwitter {
            get {
                return ResourceManager.GetString("DeveloperProfileHeaderFollowersTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Projects に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeveloperProfileHeaderProjects {
            get {
                return ResourceManager.GetString("DeveloperProfileHeaderProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeveloperProfileLinksEmail {
            get {
                return ResourceManager.GetString("DeveloperProfileLinksEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Support に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeveloperProfileSupport {
            get {
                return ResourceManager.GetString("DeveloperProfileSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeline に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeveloperProfileTimeline {
            get {
                return ResourceManager.GetString("DeveloperProfileTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Score {0:F0}% ({1}/{2}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormatWordbookRateInfo {
            get {
                return ResourceManager.GetString("FormatWordbookRateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Score: {0:F0}% ({1}/{2}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormatWordRateInfo {
            get {
                return ResourceManager.GetString("FormatWordRateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detail に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LicenseDetailPage {
            get {
                return ResourceManager.GetString("LicenseDetailPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LicenseOpen {
            get {
                return ResourceManager.GetString("LicenseOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MasterDeveloperProfileTitle {
            get {
                return ResourceManager.GetString("MasterDeveloperProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting of this app. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MasterSettingDetail {
            get {
                return ResourceManager.GetString("MasterSettingDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MasterSettingTitle {
            get {
                return ResourceManager.GetString("MasterSettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show result of the tests. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MasterStatisticsDetail {
            get {
                return ResourceManager.GetString("MasterStatisticsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Statistics に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MasterStatisticsTitle {
            get {
                return ResourceManager.GetString("MasterStatisticsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Buy books. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MasterStoreDetail {
            get {
                return ResourceManager.GetString("MasterStoreDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Store に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MasterStoreTitle {
            get {
                return ResourceManager.GetString("MasterStoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show all registered words. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MasterWordbooksCombinedDetail {
            get {
                return ResourceManager.GetString("MasterWordbooksCombinedDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Integrated Wordbook に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MasterWordbooksCombinedTitle {
            get {
                return ResourceManager.GetString("MasterWordbooksCombinedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show registered wordbooks. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MasterWordbooksDetail {
            get {
                return ResourceManager.GetString("MasterWordbooksDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wordbooks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MasterWordbooksTitle {
            get {
                return ResourceManager.GetString("MasterWordbooksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is already registered. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookAlertAlreadyExist {
            get {
                return ResourceManager.GetString("NewWordbookAlertAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Authentication failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookAlertFailedToAuth {
            get {
                return ResourceManager.GetString("NewWordbookAlertFailedToAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to read the file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookAlertFailedToLoad {
            get {
                return ResourceManager.GetString("NewWordbookAlertFailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no deleted wordbook. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookAlertRecoverNotFound {
            get {
                return ResourceManager.GetString("NewWordbookAlertRecoverNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The address is inappropriate. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookAlertWrongAddress {
            get {
                return ResourceManager.GetString("NewWordbookAlertWrongAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Authentication information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookCommonAuthTitle {
            get {
                return ResourceManager.GetString("NewWordbookCommonAuthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookCommonTitleTitle {
            get {
                return ResourceManager.GetString("NewWordbookCommonTitleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select columns. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookCsvPreviewMessage {
            get {
                return ResourceManager.GetString("NewWordbookCsvPreviewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookCsvPreviewPickerTitleDescription {
            get {
                return ResourceManager.GetString("NewWordbookCsvPreviewPickerTitleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Term に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookCsvPreviewPickerTitleHead {
            get {
                return ResourceManager.GetString("NewWordbookCsvPreviewPickerTitleHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Columns に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookCsvPreviewTitle {
            get {
                return ResourceManager.GetString("NewWordbookCsvPreviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   utf8 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookDefaultEncoding {
            get {
                return ResourceManager.GetString("NewWordbookDefaultEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select character code for CSV file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookEncodingMessage {
            get {
                return ResourceManager.GetString("NewWordbookEncodingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Character code に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookEntryListEncoding {
            get {
                return ResourceManager.GetString("NewWordbookEntryListEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookEntryListId {
            get {
                return ResourceManager.GetString("NewWordbookEntryListId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    (Optional) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookEntryListOptional {
            get {
                return ResourceManager.GetString("NewWordbookEntryListOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookEntryListPassword {
            get {
                return ResourceManager.GetString("NewWordbookEntryListPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookEntryListTitle {
            get {
                return ResourceManager.GetString("NewWordbookEntryListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookEntryListUrl {
            get {
                return ResourceManager.GetString("NewWordbookEntryListUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select the word book to restore. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookRecoverMessage {
            get {
                return ResourceManager.GetString("NewWordbookRecoverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wordbook に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookRecoverTitle {
            get {
                return ResourceManager.GetString("NewWordbookRecoverTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please input the title. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookRequestTitleMessage {
            get {
                return ResourceManager.GetString("NewWordbookRequestTitleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can specify the address of HTTP or SMB / CIFS (Windows Share).
        ///Please enter ID and password if necessary.
        ///An example of the SMB / CIFS address is shown below.
        ///&quot;smb://UserName:Password@ServerIP/ShareName/...&quot;
        ///&quot;\\servername\ShareName\...&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookTabCsvAuthMessage {
            get {
                return ResourceManager.GetString("NewWordbookTabCsvAuthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preview に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookTabCsvColumnButtonPreview {
            get {
                return ResourceManager.GetString("NewWordbookTabCsvColumnButtonPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Explanation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookTabCsvColumnPickerDetail {
            get {
                return ResourceManager.GetString("NewWordbookTabCsvColumnPickerDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Term に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookTabCsvColumnPickerHead {
            get {
                return ResourceManager.GetString("NewWordbookTabCsvColumnPickerHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select columns に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookTabCsvColumnTitle {
            get {
                return ResourceManager.GetString("NewWordbookTabCsvColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookTabCsvEncodeButton {
            get {
                return ResourceManager.GetString("NewWordbookTabCsvEncodeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select character code for CSV file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookTabCsvEncodeMessage {
            get {
                return ResourceManager.GetString("NewWordbookTabCsvEncodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV/XLSX に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookTabCsvTitle {
            get {
                return ResourceManager.GetString("NewWordbookTabCsvTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can change the title later. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookTabCsvTitleMessage {
            get {
                return ResourceManager.GetString("NewWordbookTabCsvTitleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy and paste the content of special-gift-page. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookTabImpressAutoMessage {
            get {
                return ResourceManager.GetString("NewWordbookTabImpressAutoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Smart entry に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookTabImpressAutoTitle {
            get {
                return ResourceManager.GetString("NewWordbookTabImpressAutoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gifts available に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookTabImpressGetButton {
            get {
                return ResourceManager.GetString("NewWordbookTabImpressGetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can also browse books with gifts from Store page. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookTabImpressGetMessage {
            get {
                return ResourceManager.GetString("NewWordbookTabImpressGetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Obtain に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookTabImpressGetTitle {
            get {
                return ResourceManager.GetString("NewWordbookTabImpressGetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recover に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookTabImpressRecoverButton {
            get {
                return ResourceManager.GetString("NewWordbookTabImpressRecoverButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recover deleted wordbooks. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookTabImpressRecoverMessage {
            get {
                return ResourceManager.GetString("NewWordbookTabImpressRecoverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recovery に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookTabImpressRecoverTitle {
            get {
                return ResourceManager.GetString("NewWordbookTabImpressRecoverTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   impress books に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookTabImpressTitle {
            get {
                return ResourceManager.GetString("NewWordbookTabImpressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Suggest from URL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookTabImpressTitleFromUrl {
            get {
                return ResourceManager.GetString("NewWordbookTabImpressTitleFromUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can change the title later.
        ///If you don&apos;t enter now, it is automatically set.
        ///You may use suggested title. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookTabImpressTitleMessage {
            get {
                return ResourceManager.GetString("NewWordbookTabImpressTitleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookToolbarItemCancel {
            get {
                return ResourceManager.GetString("NewWordbookToolbarItemCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookToolbarItemSave {
            get {
                return ResourceManager.GetString("NewWordbookToolbarItemSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderActionMessage {
            get {
                return ResourceManager.GetString("OrderActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderAscending {
            get {
                return ResourceManager.GetString("OrderAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   * に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderCurrentMark {
            get {
                return ResourceManager.GetString("OrderCurrentMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Descending) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderDescending {
            get {
                return ResourceManager.GetString("OrderDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Term に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderEnumHeadword {
            get {
                return ResourceManager.GetString("OrderEnumHeadword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderEnumOriginal {
            get {
                return ResourceManager.GetString("OrderEnumOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Random に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderEnumRandom {
            get {
                return ResourceManager.GetString("OrderEnumRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Score に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderEnumScore {
            get {
                return ResourceManager.GetString("OrderEnumScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderEnumTitle {
            get {
                return ResourceManager.GetString("OrderEnumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderEnumUrl {
            get {
                return ResourceManager.GetString("OrderEnumUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://github.com/kurema/WordbookImpressApp/blob/master/LICENSE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProfileAppLicenseUrl {
            get {
                return ResourceManager.GetString("ProfileAppLicenseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://github.com/kurema/WordbookImpressApp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProfileAppProjectUrl {
            get {
                return ResourceManager.GetString("ProfileAppProjectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://github.com/kurema/WordbookImpressApp/wiki に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProfileAppWikiUrl {
            get {
                return ResourceManager.GetString("ProfileAppWikiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   B077X71C4C に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProfileDeveloperAccountsAmazonKindle {
            get {
                return ResourceManager.GetString("ProfileDeveloperAccountsAmazonKindle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   kurema に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProfileDeveloperAccountsGithub {
            get {
                return ResourceManager.GetString("ProfileDeveloperAccountsGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   kurema_makoto に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProfileDeveloperAccountsTwitter {
            get {
                return ResourceManager.GetString("ProfileDeveloperAccountsTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   kurema に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProfileDeveloperName {
            get {
                return ResourceManager.GetString("ProfileDeveloperName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select:Correct:Wrong:Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string QuizWordChoiceBottomMessage {
            get {
                return ResourceManager.GetString("QuizWordChoiceBottomMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   true:True::false:False に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string QuizWordChoiceWordMatch {
            get {
                return ResourceManager.GetString("QuizWordChoiceWordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display license of this application. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingAboutLicenseAppDetail {
            get {
                return ResourceManager.GetString("SettingAboutLicenseAppDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   License に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingAboutLicenseAppTitle {
            get {
                return ResourceManager.GetString("SettingAboutLicenseAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   License details for open-source software. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingAboutLicenseOSSDetail {
            get {
                return ResourceManager.GetString("SettingAboutLicenseOSSDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open-source licenses に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingAboutLicenseOSSTitle {
            get {
                return ResourceManager.GetString("SettingAboutLicenseOSSTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingAboutProjectPage {
            get {
                return ResourceManager.GetString("SettingAboutProjectPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingAboutTitle {
            get {
                return ResourceManager.GetString("SettingAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set up calendar demo. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingDebugDemoCalendarDetail {
            get {
                return ResourceManager.GetString("SettingDebugDemoCalendarDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calendar Demo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingDebugDemoCalendarTitle {
            get {
                return ResourceManager.GetString("SettingDebugDemoCalendarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is deleted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingDebugInitTutorialAlertMessage {
            get {
                return ResourceManager.GetString("SettingDebugInitTutorialAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deletion に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingDebugInitTutorialAlertTitle {
            get {
                return ResourceManager.GetString("SettingDebugInitTutorialAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete the tutorial completion file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingDebugInitTutorialDetail {
            get {
                return ResourceManager.GetString("SettingDebugInitTutorialDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initialize tutorial に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingDebugInitTutorialTitle {
            get {
                return ResourceManager.GetString("SettingDebugInitTutorialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Debug に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingDebugTitle {
            get {
                return ResourceManager.GetString("SettingDebugTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initialize authentification data for impress books. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingInitAuthDetail {
            get {
                return ResourceManager.GetString("SettingInitAuthDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Authentification data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingInitAuthName {
            get {
                return ResourceManager.GetString("SettingInitAuthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete {0}? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingInitConfirmation {
            get {
                return ResourceManager.GetString("SettingInitConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initialize score of the quiz. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingInitStatisticsDetail {
            get {
                return ResourceManager.GetString("SettingInitStatisticsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Score data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingInitStatisticsName {
            get {
                return ResourceManager.GetString("SettingInitStatisticsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initialize data of clicked link and obtained gifts. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingInitStoreStatisticsDetail {
            get {
                return ResourceManager.GetString("SettingInitStoreStatisticsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Store data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingInitStoreStatisticsName {
            get {
                return ResourceManager.GetString("SettingInitStoreStatisticsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initialize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingInitTitle {
            get {
                return ResourceManager.GetString("SettingInitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initialize all wordbooks data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingInitWordbookDetail {
            get {
                return ResourceManager.GetString("SettingInitWordbookDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wordbooks data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingInitWordbookName {
            get {
                return ResourceManager.GetString("SettingInitWordbookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} choices に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizChoiceChoice {
            get {
                return ResourceManager.GetString("SettingQuizChoiceChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of choices is {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizChoiceDetail {
            get {
                return ResourceManager.GetString("SettingQuizChoiceDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the number of choices. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizChoiceMessage {
            get {
                return ResourceManager.GetString("SettingQuizChoiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of choices に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizChoiceTitle {
            get {
                return ResourceManager.GetString("SettingQuizChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} time(s). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectCountChoice {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectCountChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip after you answer {0} time(s) correctly. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectCountDetailFalse {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectCountDetailFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do not skip. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectCountDetailTrue {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectCountDetailTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip after you pick correct answer ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectCountMessage {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectCountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of choice answered correctly に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectCountTitle {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectCountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip if you get score more than {1}% in {0} trial. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectRateDetailFalse {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectRateDetailFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do not skip. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectRateDetailTrue {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectRateDetailTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To answer correctly does not always mean you know the correct answer.
        ///You can prove it by good number of trial.
        ///Basics are important.
        ///That&apos;s why both the rate and the count is required. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectRatePageExplanationExplanationAlert {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectRatePageExplanationExplanationAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get hint. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectRatePageExplanationExplanationDetail {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectRatePageExplanationExplanationDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get hint. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectRatePageExplanationExplanationMessage {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectRatePageExplanationExplanationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} time(s). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectRatePageRequirementCorrectCountChoice {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectRatePageRequirementCorrectCountChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the required number of correct answers. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectRatePageRequirementCorrectCountChoiceMessage {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectRatePageRequirementCorrectCountChoiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip after you answer {0} time(s) with enough correct answer rate. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectRatePageRequirementCorrectCountDetailFalse {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectRatePageRequirementCorrectCountDetailFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do not skip. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectRatePageRequirementCorrectCountDetailTrue {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectRatePageRequirementCorrectCountDetailTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectRatePageRequirementCorrectRateChoice {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectRatePageRequirementCorrectRateChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the required rate of correct answers. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectRatePageRequirementCorrectRateChoiceMessage {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectRatePageRequirementCorrectRateChoiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip if you get score of {0}% after required trials. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectRatePageRequirementCorrectRateDetailFalse {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectRatePageRequirementCorrectRateDetailFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do not skip. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectRatePageRequirementCorrectRateDetailTrue {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectRatePageRequirementCorrectRateDetailTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Requirement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectRatePageRequirementTitle {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectRatePageRequirementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rate of correct answers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectRateTitle {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectRateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip setting is ignored once after... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionIgnoreTimeSpanChoiceMessage {
            get {
                return ResourceManager.GetString("SettingQuizConditionIgnoreTimeSpanChoiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do not ignore skip setting. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionIgnoreTimeSpanChoiceNever {
            get {
                return ResourceManager.GetString("SettingQuizConditionIgnoreTimeSpanChoiceNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip setting is ignored once after {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionIgnoreTimeSpanDetailFalse {
            get {
                return ResourceManager.GetString("SettingQuizConditionIgnoreTimeSpanDetailFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do not ignore skip setting. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionIgnoreTimeSpanDetailTrue {
            get {
                return ResourceManager.GetString("SettingQuizConditionIgnoreTimeSpanDetailTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [:g:] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionIgnoreTimeSpanTimeSpanFormat {
            get {
                return ResourceManager.GetString("SettingQuizConditionIgnoreTimeSpanTimeSpanFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grace period に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionIgnoreTimeSpanTitle {
            get {
                return ResourceManager.GetString("SettingQuizConditionIgnoreTimeSpanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do not skip marked word. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionRememberedDetailFalse {
            get {
                return ResourceManager.GetString("SettingQuizConditionRememberedDetailFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip marked word. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionRememberedDetailTrue {
            get {
                return ResourceManager.GetString("SettingQuizConditionRememberedDetailTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checked word に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionRememberedTitle {
            get {
                return ResourceManager.GetString("SettingQuizConditionRememberedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Requirement to skip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionTitle {
            get {
                return ResourceManager.GetString("SettingQuizConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do not skip. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionWordNotSkip {
            get {
                return ResourceManager.GetString("SettingQuizConditionWordNotSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quiz に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizTitle {
            get {
                return ResourceManager.GetString("SettingQuizTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select Amazon Associate ID (For amazon.co.jp). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStatisticsAmazonAssociateIdChoiceMessage {
            get {
                return ResourceManager.GetString("SettingStatisticsAmazonAssociateIdChoiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID of developer. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStatisticsAmazonAssociateIdChoiceProgrammer {
            get {
                return ResourceManager.GetString("SettingStatisticsAmazonAssociateIdChoiceProgrammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set up Amazon Associate ID. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStatisticsAmazonAssociateIdDetail {
            get {
                return ResourceManager.GetString("SettingStatisticsAmazonAssociateIdDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Amazon Associate ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStatisticsAmazonAssociateIdTitle {
            get {
                return ResourceManager.GetString("SettingStatisticsAmazonAssociateIdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} times. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStatisticsDailyQuestionChoice {
            get {
                return ResourceManager.GetString("SettingStatisticsDailyQuestionChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select standard number of quiz per day. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStatisticsDailyQuestionChoiceMessage {
            get {
                return ResourceManager.GetString("SettingStatisticsDailyQuestionChoiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The less the number, The deeper the color of the calendar. Current {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStatisticsDailyQuestionDetail {
            get {
                return ResourceManager.GetString("SettingStatisticsDailyQuestionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Standard # of quiz per day に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStatisticsDailyQuestionTitle {
            get {
                return ResourceManager.GetString("SettingStatisticsDailyQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Statistics に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStatisticsTitle {
            get {
                return ResourceManager.GetString("SettingStatisticsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The test with no answer is not listed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStatisticsZeroAnswerDetailFalse {
            get {
                return ResourceManager.GetString("SettingStatisticsZeroAnswerDetailFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The test with no answer is listed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStatisticsZeroAnswerDetailTrue {
            get {
                return ResourceManager.GetString("SettingStatisticsZeroAnswerDetailTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show empty result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStatisticsZeroAnswerTitle {
            get {
                return ResourceManager.GetString("SettingStatisticsZeroAnswerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Function around impress books is disabled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStoreEnableImpressDetailFalse {
            get {
                return ResourceManager.GetString("SettingStoreEnableImpressDetailFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Function around impress books is enabled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStoreEnableImpressDetailTrue {
            get {
                return ResourceManager.GetString("SettingStoreEnableImpressDetailTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Impress books functions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStoreEnableImpressTitle {
            get {
                return ResourceManager.GetString("SettingStoreEnableImpressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prefer ebooks. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStorePreferPrintedDetailFalse {
            get {
                return ResourceManager.GetString("SettingStorePreferPrintedDetailFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prefer printed books に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStorePreferPrintedDetailTrue {
            get {
                return ResourceManager.GetString("SettingStorePreferPrintedDetailTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Book A/D preference に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStorePreferPrintedTitle {
            get {
                return ResourceManager.GetString("SettingStorePreferPrintedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Amazon
        ///[DetailPageURL]
        ///
        ///yodobashi.com
        ///https://www.yodobashi.com/category/81001/?word=[ISBN,EAN,Title]
        ///
        ///楽天ブックス
        ///https://books.rakuten.co.jp/search/nm?sitem=[ISBN,EAN,Title] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStoreStoreChoiceChoices {
            get {
                return ResourceManager.GetString("SettingStoreStoreChoiceChoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select your favorite Store. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStoreStoreChoiceMessage {
            get {
                return ResourceManager.GetString("SettingStoreStoreChoiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change setting of Store you buy books. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStoreStoreDetail {
            get {
                return ResourceManager.GetString("SettingStoreStoreDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Favorite Store に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStoreStoreTitle {
            get {
                return ResourceManager.GetString("SettingStoreStoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Store に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStoreTitle {
            get {
                return ResourceManager.GetString("SettingStoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Support に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingSupportTitle {
            get {
                return ResourceManager.GetString("SettingSupportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show tutorial. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingSupportTutorialDetail {
            get {
                return ResourceManager.GetString("SettingSupportTutorialDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tutorial に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingSupportTutorialTitle {
            get {
                return ResourceManager.GetString("SettingSupportTutorialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open wiki of this app. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingSupportWikiDetail {
            get {
                return ResourceManager.GetString("SettingSupportWikiDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wiki に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingSupportWikiTitle {
            get {
                return ResourceManager.GetString("SettingSupportWikiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Price: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SpecialInformationItemPrice {
            get {
                return ResourceManager.GetString("SpecialInformationItemPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   QR code に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SpecialInformationItemQRCode {
            get {
                return ResourceManager.GetString("SpecialInformationItemQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show books you obtained its gift.:Only show you can get new gift.:Error. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SpecialInformationObtainedSpecialChoice {
            get {
                return ResourceManager.GetString("SpecialInformationObtainedSpecialChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show books you alredy have its wordbook.:Only show you can get new wordbook.:Error. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SpecialInformationObtainedWordbookChoice {
            get {
                return ResourceManager.GetString("SpecialInformationObtainedWordbookChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Special gift:/PDF/Wordbook/Voice/None. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SpecialInformationSpecialInfo {
            get {
                return ResourceManager.GetString("SpecialInformationSpecialInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Obtained gift. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SpecialInformationSpecialInfoObtained {
            get {
                return ResourceManager.GetString("SpecialInformationSpecialInfoObtained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only show latest version.:Show all versions.:Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SpecialInformationVersionChoice {
            get {
                return ResourceManager.GetString("SpecialInformationVersionChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Continue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsButtonContinue {
            get {
                return ResourceManager.GetString("StatisticsButtonContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retry に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsButtonRetry {
            get {
                return ResourceManager.GetString("StatisticsButtonRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsButtonTweet {
            get {
                return ResourceManager.GetString("StatisticsButtonTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsOther {
            get {
                return ResourceManager.GetString("StatisticsOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Elapsed time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsPastTimeSpan {
            get {
                return ResourceManager.GetString("StatisticsPastTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Score に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsPieGraphScore {
            get {
                return ResourceManager.GetString("StatisticsPieGraphScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title:Term quiz::Description:Description quiz に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsQuizChoiceTypeParameter {
            get {
                return ResourceManager.GetString("StatisticsQuizChoiceTypeParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Correct:Wrong:Pass:Not yet:Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsQuizResultParameter {
            get {
                return ResourceManager.GetString("StatisticsQuizResultParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   First:First time.::Retry:Retry.::Continue:Continue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsQuizRetryStatusParameter {
            get {
                return ResourceManager.GetString("StatisticsQuizRetryStatusParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Score に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsRecordTitle {
            get {
                return ResourceManager.GetString("StatisticsRecordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date : {0:G} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsTestDateFormat {
            get {
                return ResourceManager.GetString("StatisticsTestDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Each : [:g:] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsTimeSpanSingleFormat {
            get {
                return ResourceManager.GetString("StatisticsTimeSpanSingleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total : [:g:] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsTimeSpanTotalFormat {
            get {
                return ResourceManager.GetString("StatisticsTimeSpanTotalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Buy &quot;{0}&quot; and get this wordbook!
        ///{1}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsTwitterMessageAd {
            get {
                return ResourceManager.GetString("StatisticsTwitterMessageAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I answered all {0} questions correctly に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsTwitterMessageAllCorrect {
            get {
                return ResourceManager.GetString("StatisticsTwitterMessageAllCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I answered all {0} questions in error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsTwitterMessageAllWrong {
            get {
                return ResourceManager.GetString("StatisticsTwitterMessageAllWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   My score was {0} / {1}({2}%) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsTwitterMessageAnswerCount {
            get {
                return ResourceManager.GetString("StatisticsTwitterMessageAnswerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I didn&apos;t answer any に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsTwitterMessageNoAnswer {
            get {
                return ResourceManager.GetString("StatisticsTwitterMessageNoAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I got a test of {0}!
        ///{2} in {1}!
        ///#wordbook_impress
        ///{3}
        ///Get the app here!
        ///https://play.google.com/store/apps/details?id=com.github.kurema.WordbookImpressApp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsTwitterMessageTotal {
            get {
                return ResourceManager.GetString("StatisticsTwitterMessageTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [:g:] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsTwitterTimeFormat {
            get {
                return ResourceManager.GetString("StatisticsTwitterTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Books of {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StoreItemsBookOfDeveloper {
            get {
                return ResourceManager.GetString("StoreItemsBookOfDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MORE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StoreItemsCardContentMore {
            get {
                return ResourceManager.GetString("StoreItemsCardContentMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インプレス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StoreItemsImpressSearchWord {
            get {
                return ResourceManager.GetString("StoreItemsImpressSearchWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Books of &quot;impress book (Japan)&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StoreItemsImpressTitle {
            get {
                return ResourceManager.GetString("StoreItemsImpressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Similar books. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StoreItemsRelatedClicked {
            get {
                return ResourceManager.GetString("StoreItemsRelatedClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Similar to {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StoreItemsRelatedClickedTitle {
            get {
                return ResourceManager.GetString("StoreItemsRelatedClickedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Books with PDF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StoreItemsSpecialEbook {
            get {
                return ResourceManager.GetString("StoreItemsSpecialEbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Books with gift に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StoreItemsSpecialLatest {
            get {
                return ResourceManager.GetString("StoreItemsSpecialLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Books with wordbook に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StoreItemsSpecialWordbook {
            get {
                return ResourceManager.GetString("StoreItemsSpecialWordbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notice に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StoreNotice {
            get {
                return ResourceManager.GetString("StoreNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Following message is requested to display in Japanese.
        ///本アプリケーション内で表示されるコンテンツの一部は、アマゾンジャパン合同会社またはその関連会社により提供されたものです。これらのコンテンツは「現状有姿」で提供されており、随時変更または削除される場合があります。
        ///価格および発送可能時期は表示された日付/時刻の時点のものであり、変更される場合があります。本商品の購入においては、購入の時点でAmazon.co.jpに表示されている価格および発送可能時期の情報が適用されます。
        ///Amazon.co.jpアソシエイト。
        ///特典情報などの一部は独自作成したデータベースを利用しています。これらは最新の情報でない可能性があります。ご自身でご確認の上ご利用ください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StoreNoticeMessage {
            get {
                return ResourceManager.GetString("StoreNoticeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date : {0:G} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestStatusDateTimeStartFormat {
            get {
                return ResourceManager.GetString("TestStatusDateTimeStartFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Score に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestStatusPieGraphScore {
            get {
                return ResourceManager.GetString("TestStatusPieGraphScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wordbook : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestStatusTargetWordbookFormat {
            get {
                return ResourceManager.GetString("TestStatusTargetWordbookFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Each: [:g:] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestStatusTimeSpanFormatEach {
            get {
                return ResourceManager.GetString("TestStatusTimeSpanFormatEach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total: [:g:] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestStatusTimeSpanFormatTotal {
            get {
                return ResourceManager.GetString("TestStatusTimeSpanFormatTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Elapsed time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestStatusTimeSpanTitle {
            get {
                return ResourceManager.GetString("TestStatusTimeSpanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total score に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestStatusTotalStatus {
            get {
                return ResourceManager.GetString("TestStatusTotalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleDeveloperProfile {
            get {
                return ResourceManager.GetString("TitleDeveloperProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleEntryWithOption {
            get {
                return ResourceManager.GetString("TitleEntryWithOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   License に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleLicense {
            get {
                return ResourceManager.GetString("TitleLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Menu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleMaster {
            get {
                return ResourceManager.GetString("TitleMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleNewWordbook {
            get {
                return ResourceManager.GetString("TitleNewWordbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preview に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleNewWordbookCsvPreview {
            get {
                return ResourceManager.GetString("TitleNewWordbookCsvPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quiz に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleQuizWordChoice {
            get {
                return ResourceManager.GetString("TitleQuizWordChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleSetting {
            get {
                return ResourceManager.GetString("TitleSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Books に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleSpecialInformation {
            get {
                return ResourceManager.GetString("TitleSpecialInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Book に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleSpecialInformationItem {
            get {
                return ResourceManager.GetString("TitleSpecialInformationItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Statistics に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleStatistics {
            get {
                return ResourceManager.GetString("TitleStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Store に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleStore {
            get {
                return ResourceManager.GetString("TitleStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Score に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleTestStatus {
            get {
                return ResourceManager.GetString("TitleTestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tutorial に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleTutorial {
            get {
                return ResourceManager.GetString("TitleTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wordbook に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleWordbook {
            get {
                return ResourceManager.GetString("TitleWordbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wordbooks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleWordbooks {
            get {
                return ResourceManager.GetString("TitleWordbooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Word に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleWordPage {
            get {
                return ResourceManager.GetString("TitleWordPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Word に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleWordsPage {
            get {
                return ResourceManager.GetString("TitleWordsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialButtonDone {
            get {
                return ResourceManager.GetString("TutorialButtonDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialButtonNext {
            get {
                return ResourceManager.GetString("TutorialButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialButtonSkip {
            get {
                return ResourceManager.GetString("TutorialButtonSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create wordbooks
        ///in CSV or XLSX. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage1Detail {
            get {
                return ResourceManager.GetString("TutorialPage1Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tutorial_sheet.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage1Image {
            get {
                return ResourceManager.GetString("TutorialPage1Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage1Title {
            get {
                return ResourceManager.GetString("TutorialPage1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Share the file
        ///via SMB/HTTP. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage2Detail {
            get {
                return ResourceManager.GetString("TutorialPage2Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tutorial_share.jpg に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage2Image {
            get {
                return ResourceManager.GetString("TutorialPage2Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Share に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage2Title {
            get {
                return ResourceManager.GetString("TutorialPage2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transfer the file here. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage3Detail {
            get {
                return ResourceManager.GetString("TutorialPage3Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tutorial_add_en.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage3Image {
            get {
                return ResourceManager.GetString("TutorialPage3Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transfer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage3Title {
            get {
                return ResourceManager.GetString("TutorialPage3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ddd に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WeekOfDaysFormat {
            get {
                return ResourceManager.GetString("WeekOfDaysFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can not this virtual wordbook. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordbookAlertCannotDelete {
            get {
                return ResourceManager.GetString("WordbookAlertCannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete this wordbook? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordbookAlertConfirmDelete {
            get {
                return ResourceManager.GetString("WordbookAlertConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total score に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordbookCombinedTitle {
            get {
                return ResourceManager.GetString("WordbookCombinedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description quiz に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordbookQuizDescription {
            get {
                return ResourceManager.GetString("WordbookQuizDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Term quiz に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordbookQuizHead {
            get {
                return ResourceManager.GetString("WordbookQuizHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter the title. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordbookRenameMessage {
            get {
                return ResourceManager.GetString("WordbookRenameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show description:Hide description:Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordbookShowDescription {
            get {
                return ResourceManager.GetString("WordbookShowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show term:Hide term:Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordbookShowHead {
            get {
                return ResourceManager.GetString("WordbookShowHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} words に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordbooksToolbarInfoWord {
            get {
                return ResourceManager.GetString("WordbooksToolbarInfoWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordbooksToolbarItemAdd {
            get {
                return ResourceManager.GetString("WordbooksToolbarItemAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordbooksToolbarItemOrder {
            get {
                return ResourceManager.GetString("WordbooksToolbarItemOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordbookToolbarItemDelete {
            get {
                return ResourceManager.GetString("WordbookToolbarItemDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordbookToolbarItemRename {
            get {
                return ResourceManager.GetString("WordbookToolbarItemRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Score に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordbookToolbarItemScore {
            get {
                return ResourceManager.GetString("WordbookToolbarItemScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordbookToolbarItemSort {
            get {
                return ResourceManager.GetString("WordbookToolbarItemSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Attention に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordCaution {
            get {
                return ResourceManager.GetString("WordCaution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Commentary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordCommentary {
            get {
                return ResourceManager.GetString("WordCommentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of correct answers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordCorrectCount {
            get {
                return ResourceManager.GetString("WordCorrectCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rate of correct answers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordCorrectRate {
            get {
                return ResourceManager.GetString("WordCorrectRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordDelete {
            get {
                return ResourceManager.GetString("WordDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordExplanation {
            get {
                return ResourceManager.GetString("WordExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   False に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordFalse {
            get {
                return ResourceManager.GetString("WordFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LAST PAGE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordPageBottomLast {
            get {
                return ResourceManager.GetString("WordPageBottomLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordPageBottomNext {
            get {
                return ResourceManager.GetString("WordPageBottomNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordPageBottomShow {
            get {
                return ResourceManager.GetString("WordPageBottomShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checked に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordPageRememberCheck {
            get {
                return ResourceManager.GetString("WordPageRememberCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dictionary.com に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordPageSearchDictionary {
            get {
                return ResourceManager.GetString("WordPageSearchDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://www.dictionary.com/browse/{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordPageSearchDictionaryUrl {
            get {
                return ResourceManager.GetString("WordPageSearchDictionaryUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Google に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordPageSearchGoogle {
            get {
                return ResourceManager.GetString("WordPageSearchGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://www.google.com/search?q={0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordPageSearchGoogleUrl {
            get {
                return ResourceManager.GetString("WordPageSearchGoogleUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wikipedia に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordPageSearchWikipedia {
            get {
                return ResourceManager.GetString("WordPageSearchWikipedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://en.wikipedia.org/wiki/{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordPageSearchWikipediaUrl {
            get {
                return ResourceManager.GetString("WordPageSearchWikipediaUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Price に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordPrice {
            get {
                return ResourceManager.GetString("WordPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   QR code に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordQRCode {
            get {
                return ResourceManager.GetString("WordQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quiz に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordQuiz {
            get {
                return ResourceManager.GetString("WordQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Report に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordReport {
            get {
                return ResourceManager.GetString("WordReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordSort {
            get {
                return ResourceManager.GetString("WordSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Store に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordStore {
            get {
                return ResourceManager.GetString("WordStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   True に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordTrue {
            get {
                return ResourceManager.GetString("WordTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordWarning {
            get {
                return ResourceManager.GetString("WordWarning", resourceCulture);
            }
        }
    }
}
