//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordbookImpressApp.Resx {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordbookImpressApp.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AlertCancel {
            get {
                return ResourceManager.GetString("AlertCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   了解 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AlertConfirmed {
            get {
                return ResourceManager.GetString("AlertConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カスタム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AlertCustom {
            get {
                return ResourceManager.GetString("AlertCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   いいえ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AlertNo {
            get {
                return ResourceManager.GetString("AlertNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   注意 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AlertWarning {
            get {
                return ResourceManager.GetString("AlertWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   はい に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AlertYes {
            get {
                return ResourceManager.GetString("AlertYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MMMM に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CalendarMonthFormat {
            get {
                return ResourceManager.GetString("CalendarMonthFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Available for hire! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeveloperProfileAvailableForHire {
            get {
                return ResourceManager.GetString("DeveloperProfileAvailableForHire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeveloperProfileBio {
            get {
                return ResourceManager.GetString("DeveloperProfileBio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Books に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeveloperProfileBooks {
            get {
                return ResourceManager.GetString("DeveloperProfileBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contact に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeveloperProfileContact {
            get {
                return ResourceManager.GetString("DeveloperProfileContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   寄付 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeveloperProfileDonationTitle {
            get {
                return ResourceManager.GetString("DeveloperProfileDonationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Followers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeveloperProfileHeaderFollowers {
            get {
                return ResourceManager.GetString("DeveloperProfileHeaderFollowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Twitter
        ///Followers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeveloperProfileHeaderFollowersTwitter {
            get {
                return ResourceManager.GetString("DeveloperProfileHeaderFollowersTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Projects に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeveloperProfileHeaderProjects {
            get {
                return ResourceManager.GetString("DeveloperProfileHeaderProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeveloperProfileLinksEmail {
            get {
                return ResourceManager.GetString("DeveloperProfileLinksEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Support に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeveloperProfileSupport {
            get {
                return ResourceManager.GetString("DeveloperProfileSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeline に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeveloperProfileTimeline {
            get {
                return ResourceManager.GetString("DeveloperProfileTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正答率{0:F0}% ({1}問中{2}問) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormatWordbookRateInfo {
            get {
                return ResourceManager.GetString("FormatWordbookRateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正答率 {0:F0}% ({1}/{2}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormatWordRateInfo {
            get {
                return ResourceManager.GetString("FormatWordRateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   詳細ページ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LicenseDetailPage {
            get {
                return ResourceManager.GetString("LicenseDetailPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LicenseOpen {
            get {
                return ResourceManager.GetString("LicenseOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}について に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MasterDeveloperProfileTitle {
            get {
                return ResourceManager.GetString("MasterDeveloperProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単語帳の設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MasterSettingDetail {
            get {
                return ResourceManager.GetString("MasterSettingDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MasterSettingTitle {
            get {
                return ResourceManager.GetString("MasterSettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テスト結果を表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MasterStatisticsDetail {
            get {
                return ResourceManager.GetString("MasterStatisticsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   成績表 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MasterStatisticsTitle {
            get {
                return ResourceManager.GetString("MasterStatisticsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   書籍を購入 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MasterStoreDetail {
            get {
                return ResourceManager.GetString("MasterStoreDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MasterStoreTitle {
            get {
                return ResourceManager.GetString("MasterStoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全ての単語帳を総合 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MasterWordbooksCombinedDetail {
            get {
                return ResourceManager.GetString("MasterWordbooksCombinedDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   総合単語帳 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MasterWordbooksCombinedTitle {
            get {
                return ResourceManager.GetString("MasterWordbooksCombinedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録済み単語帳 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MasterWordbooksDetail {
            get {
                return ResourceManager.GetString("MasterWordbooksDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単語帳 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MasterWordbooksTitle {
            get {
                return ResourceManager.GetString("MasterWordbooksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   列を選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookCsvPreviewMessage {
            get {
                return ResourceManager.GetString("NewWordbookCsvPreviewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   説明 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookCsvPreviewPickerTitleDescription {
            get {
                return ResourceManager.GetString("NewWordbookCsvPreviewPickerTitleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単語名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookCsvPreviewPickerTitleHead {
            get {
                return ResourceManager.GetString("NewWordbookCsvPreviewPickerTitleHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   項目選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewWordbookCsvPreviewTitle {
            get {
                return ResourceManager.GetString("NewWordbookCsvPreviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   並び替え に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderActionMessage {
            get {
                return ResourceManager.GetString("OrderActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderAscending {
            get {
                return ResourceManager.GetString("OrderAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   * に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderCurrentMark {
            get {
                return ResourceManager.GetString("OrderCurrentMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (降順) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderDescending {
            get {
                return ResourceManager.GetString("OrderDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単語名順 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderEnumHeadword {
            get {
                return ResourceManager.GetString("OrderEnumHeadword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   標準 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderEnumOriginal {
            get {
                return ResourceManager.GetString("OrderEnumOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ランダム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderEnumRandom {
            get {
                return ResourceManager.GetString("OrderEnumRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   成績順 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderEnumScore {
            get {
                return ResourceManager.GetString("OrderEnumScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイトル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderEnumTitle {
            get {
                return ResourceManager.GetString("OrderEnumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderEnumUrl {
            get {
                return ResourceManager.GetString("OrderEnumUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://github.com/kurema/WordbookImpressApp/blob/master/LICENSE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProfileAppLicenseUrl {
            get {
                return ResourceManager.GetString("ProfileAppLicenseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://github.com/kurema/WordbookImpressApp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProfileAppProjectUrl {
            get {
                return ResourceManager.GetString("ProfileAppProjectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://github.com/kurema/WordbookImpressApp/wiki に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProfileAppWikiUrl {
            get {
                return ResourceManager.GetString("ProfileAppWikiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   B077X71C4C に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProfileDeveloperAccountsAmazonKindle {
            get {
                return ResourceManager.GetString("ProfileDeveloperAccountsAmazonKindle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   kurema に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProfileDeveloperAccountsGithub {
            get {
                return ResourceManager.GetString("ProfileDeveloperAccountsGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   kurema_makoto に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProfileDeveloperAccountsTwitter {
            get {
                return ResourceManager.GetString("ProfileDeveloperAccountsTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   kurema に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProfileDeveloperName {
            get {
                return ResourceManager.GetString("ProfileDeveloperName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択してください:正解:不正解:エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string QuizWordChoiceBottomMessage {
            get {
                return ResourceManager.GetString("QuizWordChoiceBottomMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このアプリのライセンスを表示。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingAboutLicenseAppDetail {
            get {
                return ResourceManager.GetString("SettingAboutLicenseAppDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ライセンス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingAboutLicenseAppTitle {
            get {
                return ResourceManager.GetString("SettingAboutLicenseAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オープンソースソフトウェアに関するライセンスの詳細 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingAboutLicenseOSSDetail {
            get {
                return ResourceManager.GetString("SettingAboutLicenseOSSDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オープンソースライセンス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingAboutLicenseOSSTitle {
            get {
                return ResourceManager.GetString("SettingAboutLicenseOSSTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロジェクトページ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingAboutProjectPage {
            get {
                return ResourceManager.GetString("SettingAboutProjectPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}について に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingAboutTitle {
            get {
                return ResourceManager.GetString("SettingAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}を削除しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingDebugInitTutorialAlertMessage {
            get {
                return ResourceManager.GetString("SettingDebugInitTutorialAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingDebugInitTutorialAlertTitle {
            get {
                return ResourceManager.GetString("SettingDebugInitTutorialAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チュートリアル完了ファイルを削除します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingDebugInitTutorialDetail {
            get {
                return ResourceManager.GetString("SettingDebugInitTutorialDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チュートリアル初期設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingDebugInitTutorialTitle {
            get {
                return ResourceManager.GetString("SettingDebugInitTutorialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デバッグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingDebugTitle {
            get {
                return ResourceManager.GetString("SettingDebugTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizChoiceChoice {
            get {
                return ResourceManager.GetString("SettingQuizChoiceChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択肢の数は{0}個です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizChoiceDetail {
            get {
                return ResourceManager.GetString("SettingQuizChoiceDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択肢の数を選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizChoiceMessage {
            get {
                return ResourceManager.GetString("SettingQuizChoiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択肢 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizChoiceTitle {
            get {
                return ResourceManager.GetString("SettingQuizChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}回 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectCountChoice {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectCountChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}回正解した単語をスキップします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectCountDetailFalse {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectCountDetailFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正解数に関わらず出題します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectCountDetailTrue {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectCountDetailTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スキップする正解数を選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectCountMessage {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectCountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正解数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectCountTitle {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectCountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}問以上出題した結果{1}%正解した単語をスキップします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectRateDetailFalse {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectRateDetailFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正解率に関わらず出題します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectRateDetailTrue {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectRateDetailTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出題問題数が少ない間はたまたま正解してしまい正解率が高くなってしまう事があります。
        ///適切な正解率を得るには一定回数の出題が必要です。
        ///また基本もおろそかにしない事が大事です。
        ///以下の条件を片方でも満たさない場合には出題します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectRatePageExplanationExplanationAlert {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectRatePageExplanationExplanationAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この条件に関して説明します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectRatePageExplanationExplanationDetail {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectRatePageExplanationExplanationDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この条件に関して説明します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectRatePageExplanationExplanationMessage {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectRatePageExplanationExplanationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}問 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectRatePageRequirementCorrectCountChoice {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectRatePageRequirementCorrectCountChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スキップに必要な出題数を選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectRatePageRequirementCorrectCountChoiceMessage {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectRatePageRequirementCorrectCountChoiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出題数が{0}問未満の場合は出題します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectRatePageRequirementCorrectCountDetailFalse {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectRatePageRequirementCorrectCountDetailFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出題数に関わらず出題します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectRatePageRequirementCorrectCountDetailTrue {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectRatePageRequirementCorrectCountDetailTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectRatePageRequirementCorrectRateChoice {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectRatePageRequirementCorrectRateChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スキップする正解率を選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectRatePageRequirementCorrectRateChoiceMessage {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectRatePageRequirementCorrectRateChoiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正解率が{0}%未満の場合は出題します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectRatePageRequirementCorrectRateDetailFalse {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectRatePageRequirementCorrectRateDetailFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正解率に関わらず出題します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectRatePageRequirementCorrectRateDetailTrue {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectRatePageRequirementCorrectRateDetailTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正解率条件 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectRatePageRequirementTitle {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectRatePageRequirementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正解率 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionCorrectRateTitle {
            get {
                return ResourceManager.GetString("SettingQuizConditionCorrectRateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   条件によらず出題されるようになるまでの期間を指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionIgnoreTimeSpanChoiceMessage {
            get {
                return ResourceManager.GetString("SettingQuizConditionIgnoreTimeSpanChoiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出題しない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionIgnoreTimeSpanChoiceNever {
            get {
                return ResourceManager.GetString("SettingQuizConditionIgnoreTimeSpanChoiceNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最後に正解してから{0}経過した場合には通常通り出題します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionIgnoreTimeSpanDetailFalse {
            get {
                return ResourceManager.GetString("SettingQuizConditionIgnoreTimeSpanDetailFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   条件を満たさない場合は出題しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionIgnoreTimeSpanDetailTrue {
            get {
                return ResourceManager.GetString("SettingQuizConditionIgnoreTimeSpanDetailTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [if:Days:[Days]日][if:Hours:[Hours]時間][if:Minutes:[Minutes]分][if:Seconds:[Seconds]秒] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionIgnoreTimeSpanTimeSpanFormat {
            get {
                return ResourceManager.GetString("SettingQuizConditionIgnoreTimeSpanTimeSpanFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   条件無視期間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionIgnoreTimeSpanTitle {
            get {
                return ResourceManager.GetString("SettingQuizConditionIgnoreTimeSpanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クイズで記憶済みにチェックした単語も出題します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionRememberedDetailFalse {
            get {
                return ResourceManager.GetString("SettingQuizConditionRememberedDetailFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クイズで記憶済みにチェックした単語をスキップします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionRememberedDetailTrue {
            get {
                return ResourceManager.GetString("SettingQuizConditionRememberedDetailTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   記憶済み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionRememberedTitle {
            get {
                return ResourceManager.GetString("SettingQuizConditionRememberedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クイズ出題条件 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionTitle {
            get {
                return ResourceManager.GetString("SettingQuizConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スキップしない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizConditionWordNotSkip {
            get {
                return ResourceManager.GetString("SettingQuizConditionWordNotSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クイズ設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingQuizTitle {
            get {
                return ResourceManager.GetString("SettingQuizTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Amazon アソシエイトIDを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStatisticsAmazonAssociateIdChoiceMessage {
            get {
                return ResourceManager.GetString("SettingStatisticsAmazonAssociateIdChoiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリ製作者のID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStatisticsAmazonAssociateIdChoiceProgrammer {
            get {
                return ResourceManager.GetString("SettingStatisticsAmazonAssociateIdChoiceProgrammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スコア共有時に使用されるAmazon アソシエイトIDを設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStatisticsAmazonAssociateIdDetail {
            get {
                return ResourceManager.GetString("SettingStatisticsAmazonAssociateIdDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Amazon アソシエイトID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStatisticsAmazonAssociateIdTitle {
            get {
                return ResourceManager.GetString("SettingStatisticsAmazonAssociateIdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}問 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStatisticsDailyQuestionChoice {
            get {
                return ResourceManager.GetString("SettingStatisticsDailyQuestionChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回答数目安を選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStatisticsDailyQuestionChoiceMessage {
            get {
                return ResourceManager.GetString("SettingStatisticsDailyQuestionChoiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   成績一覧ページのカレンダーグラフに反映されます。現在{0}問。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStatisticsDailyQuestionDetail {
            get {
                return ResourceManager.GetString("SettingStatisticsDailyQuestionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一日当たりの回答数目安 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStatisticsDailyQuestionTitle {
            get {
                return ResourceManager.GetString("SettingStatisticsDailyQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   成績一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStatisticsTitle {
            get {
                return ResourceManager.GetString("SettingStatisticsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無回答の場合成績一覧に表示しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStatisticsZeroAnswerDetailFalse {
            get {
                return ResourceManager.GetString("SettingStatisticsZeroAnswerDetailFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無回答でも成績一覧に表示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStatisticsZeroAnswerDetailTrue {
            get {
                return ResourceManager.GetString("SettingStatisticsZeroAnswerDetailTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無回答を表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStatisticsZeroAnswerTitle {
            get {
                return ResourceManager.GetString("SettingStatisticsZeroAnswerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストア及びインプレスブックス単語帳機能をオフにします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStoreEnableImpressDetailFalse {
            get {
                return ResourceManager.GetString("SettingStoreEnableImpressDetailFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストア及びインプレスブックス単語帳機能をオンにします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStoreEnableImpressDetailTrue {
            get {
                return ResourceManager.GetString("SettingStoreEnableImpressDetailTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インプレスブックス関連機能 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStoreEnableImpressTitle {
            get {
                return ResourceManager.GetString("SettingStoreEnableImpressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   電子書籍を優先して表示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStorePreferPrintedDetailFalse {
            get {
                return ResourceManager.GetString("SettingStorePreferPrintedDetailFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   印刷版の本を優先して表示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStorePreferPrintedDetailTrue {
            get {
                return ResourceManager.GetString("SettingStorePreferPrintedDetailTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   印刷版を優先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStorePreferPrintedTitle {
            get {
                return ResourceManager.GetString("SettingStorePreferPrintedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Amazon
        ///[DetailPageURL]
        ///
        ///yodobashi.com
        ///https://www.yodobashi.com/category/81001/?word=[ISBN,EAN,Title]
        ///
        ///楽天ブックス
        ///https://books.rakuten.co.jp/search/nm?sitem=[ISBN,EAN,Title] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStoreStoreChoiceChoices {
            get {
                return ResourceManager.GetString("SettingStoreStoreChoiceChoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リンクで開くストアを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStoreStoreChoiceMessage {
            get {
                return ResourceManager.GetString("SettingStoreStoreChoiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リンクを開く際のストアを設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStoreStoreDetail {
            get {
                return ResourceManager.GetString("SettingStoreStoreDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リンクを開くストア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStoreStoreTitle {
            get {
                return ResourceManager.GetString("SettingStoreStoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStoreTitle {
            get {
                return ResourceManager.GetString("SettingStoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サポート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingSupportTitle {
            get {
                return ResourceManager.GetString("SettingSupportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初回チュートリアルを表示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingSupportTutorialDetail {
            get {
                return ResourceManager.GetString("SettingSupportTutorialDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チュートリアル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingSupportTutorialTitle {
            get {
                return ResourceManager.GetString("SettingSupportTutorialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このアプリのWikiを開きます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingSupportWikiDetail {
            get {
                return ResourceManager.GetString("SettingSupportWikiDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wiki に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingSupportWikiTitle {
            get {
                return ResourceManager.GetString("SettingSupportWikiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   価格: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SpecialInformationItemPrice {
            get {
                return ResourceManager.GetString("SpecialInformationItemPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   QRコード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SpecialInformationItemQRCode {
            get {
                return ResourceManager.GetString("SpecialInformationItemQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   特典:/本文PDF/単語帳/音声/特典なし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SpecialInformationSpecialInfo {
            get {
                return ResourceManager.GetString("SpecialInformationSpecialInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最新版のみ表示:以前のバージョンを表示:エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SpecialInformationVersionChoice {
            get {
                return ResourceManager.GetString("SpecialInformationVersionChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コンティニュー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsButtonContinue {
            get {
                return ResourceManager.GetString("StatisticsButtonContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リトライ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsButtonRetry {
            get {
                return ResourceManager.GetString("StatisticsButtonRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsButtonTweet {
            get {
                return ResourceManager.GetString("StatisticsButtonTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その他 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsOther {
            get {
                return ResourceManager.GetString("StatisticsOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   経過時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsPastTimeSpan {
            get {
                return ResourceManager.GetString("StatisticsPastTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スコア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsPieGraphScore {
            get {
                return ResourceManager.GetString("StatisticsPieGraphScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title:単語当てクイズ::Description:説明当てクイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsQuizChoiceTypeParameter {
            get {
                return ResourceManager.GetString("StatisticsQuizChoiceTypeParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正解:誤答:未回答:未出題:エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsQuizResultParameter {
            get {
                return ResourceManager.GetString("StatisticsQuizResultParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   First:初回::Retry:リトライ::Continue:コンティニュー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsQuizRetryStatusParameter {
            get {
                return ResourceManager.GetString("StatisticsQuizRetryStatusParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   成績 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsRecordTitle {
            get {
                return ResourceManager.GetString("StatisticsRecordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   試験日時 : {0:yyyy\年MM\月dd\日 tt h\時mm\分\開\始 } に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsTestDateFormat {
            get {
                return ResourceManager.GetString("StatisticsTestDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1問当たり : [if:TotalMinutesFloor:[TotalMinutesFloor:\{0:00\}]分][Seconds:\{0:00\}]秒 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsTimeSpanSingleFormat {
            get {
                return ResourceManager.GetString("StatisticsTimeSpanSingleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   合計 : [if:TotalMinutesFloor:[TotalMinutesFloor:\{0:00\}]分][Seconds:\{0:00\}]秒 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsTimeSpanTotalFormat {
            get {
                return ResourceManager.GetString("StatisticsTimeSpanTotalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この単語帳は「{0}」を買えば付いてきます。
        ///{1}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsTwitterMessageAd {
            get {
                return ResourceManager.GetString("StatisticsTwitterMessageAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}問全て正解しました！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsTwitterMessageAllCorrect {
            get {
                return ResourceManager.GetString("StatisticsTwitterMessageAllCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}問全て間違えました！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsTwitterMessageAllWrong {
            get {
                return ResourceManager.GetString("StatisticsTwitterMessageAllWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}問中{1}問({2}%)正解しました！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsTwitterMessageAnswerCount {
            get {
                return ResourceManager.GetString("StatisticsTwitterMessageAnswerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1問も解答しませんでした！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsTwitterMessageNoAnswer {
            get {
                return ResourceManager.GetString("StatisticsTwitterMessageNoAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}のクイズを{1}で{2}
        ///#wordbook_impress
        ///{3}
        ///単語帳アプリは現在開発中
        ///https://github.com/kurema/WordbookImpressApp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsTwitterMessageTotal {
            get {
                return ResourceManager.GetString("StatisticsTwitterMessageTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [if:TotalMinutesFloor:[TotalMinutesFloor:{0:00}]分][Seconds:{0:00}]秒 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatisticsTwitterTimeFormat {
            get {
                return ResourceManager.GetString("StatisticsTwitterTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の本 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StoreItemsBookOfDeveloper {
            get {
                return ResourceManager.GetString("StoreItemsBookOfDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インプレス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StoreItemsImpressSearchWord {
            get {
                return ResourceManager.GetString("StoreItemsImpressSearchWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インプレスブックスの本 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StoreItemsImpressTitle {
            get {
                return ResourceManager.GetString("StoreItemsImpressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   以前クリックした本に関連 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StoreItemsRelatedClicked {
            get {
                return ResourceManager.GetString("StoreItemsRelatedClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}に関連 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StoreItemsRelatedClickedTitle {
            get {
                return ResourceManager.GetString("StoreItemsRelatedClickedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   本文PDFが手に入る本 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StoreItemsSpecialEbook {
            get {
                return ResourceManager.GetString("StoreItemsSpecialEbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最近追加された特典本 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StoreItemsSpecialLatest {
            get {
                return ResourceManager.GetString("StoreItemsSpecialLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単語帳が手に入る本 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StoreItemsSpecialWordbook {
            get {
                return ResourceManager.GetString("StoreItemsSpecialWordbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   利用時の注意 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StoreNotice {
            get {
                return ResourceManager.GetString("StoreNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   本アプリケーション内で表示されるコンテンツの一部は、アマゾンジャパン合同会社またはその関連会社により提供されたものです。これらのコンテンツは「現状有姿」で提供されており、随時変更または削除される場合があります。
        ///価格および発送可能時期は表示された日付/時刻の時点のものであり、変更される場合があります。本商品の購入においては、購入の時点でAmazon.co.jpに表示されている価格および発送可能時期の情報が適用されます。
        ///Amazon.co.jpアソシエイト。
        ///特典情報などの一部は独自作成したデータベースを利用しています。これらは最新の情報でない可能性があります。ご自身でご確認の上ご利用ください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StoreNoticeMessage {
            get {
                return ResourceManager.GetString("StoreNoticeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   試験日時 : {0:yyyy\年MM\月dd\日 tt h\時mm\分\開\始 } に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestStatusDateTimeStartFormat {
            get {
                return ResourceManager.GetString("TestStatusDateTimeStartFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スコア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestStatusPieGraphScore {
            get {
                return ResourceManager.GetString("TestStatusPieGraphScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象単語帳 : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestStatusTargetWordbookFormat {
            get {
                return ResourceManager.GetString("TestStatusTargetWordbookFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1問当たり : [if:TotalMinutesFloor:[TotalMinutesFloor:{0:00}]分][Seconds:{0:00}]秒 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestStatusTimeSpanFormatEach {
            get {
                return ResourceManager.GetString("TestStatusTimeSpanFormatEach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   合計 : [if:TotalMinutesFloor:[TotalMinutesFloor:{0:00}]分][Seconds:{0:00}]秒 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestStatusTimeSpanFormatTotal {
            get {
                return ResourceManager.GetString("TestStatusTimeSpanFormatTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   経過時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestStatusTimeSpanTitle {
            get {
                return ResourceManager.GetString("TestStatusTimeSpanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全体成績 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestStatusTotalStatus {
            get {
                return ResourceManager.GetString("TestStatusTotalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロフィール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleDeveloperProfile {
            get {
                return ResourceManager.GetString("TitleDeveloperProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleEntryWithOption {
            get {
                return ResourceManager.GetString("TitleEntryWithOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ライセンス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleLicense {
            get {
                return ResourceManager.GetString("TitleLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メニュー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleMaster {
            get {
                return ResourceManager.GetString("TitleMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プレビュー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleNewWordbookCsvPreview {
            get {
                return ResourceManager.GetString("TitleNewWordbookCsvPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleQuizWordChoice {
            get {
                return ResourceManager.GetString("TitleQuizWordChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleSetting {
            get {
                return ResourceManager.GetString("TitleSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   書籍一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleSpecialInformation {
            get {
                return ResourceManager.GetString("TitleSpecialInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   書籍詳細 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleSpecialInformationItem {
            get {
                return ResourceManager.GetString("TitleSpecialInformationItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   成績 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleStatistics {
            get {
                return ResourceManager.GetString("TitleStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleStore {
            get {
                return ResourceManager.GetString("TitleStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   成績 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleTestStatus {
            get {
                return ResourceManager.GetString("TitleTestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チュートリアル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleTutorial {
            get {
                return ResourceManager.GetString("TitleTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単語帳 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleWordbook {
            get {
                return ResourceManager.GetString("TitleWordbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単語帳一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleWordbooks {
            get {
                return ResourceManager.GetString("TitleWordbooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleWordPage {
            get {
                return ResourceManager.GetString("TitleWordPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleWordsPage {
            get {
                return ResourceManager.GetString("TitleWordsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialButtonDone {
            get {
                return ResourceManager.GetString("TutorialButtonDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialButtonNext {
            get {
                return ResourceManager.GetString("TutorialButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スキップ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialButtonSkip {
            get {
                return ResourceManager.GetString("TutorialButtonSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   店頭やネットで
        ///インプレスブックスの対象書籍を購入 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage1Detail {
            get {
                return ResourceManager.GetString("TutorialPage1Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   本を買う に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage1Title {
            get {
                return ResourceManager.GetString("TutorialPage1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   公式サイトから特典を取得 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage2Detail {
            get {
                return ResourceManager.GetString("TutorialPage2Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   特典を得る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage2Title {
            get {
                return ResourceManager.GetString("TutorialPage2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このアプリで単語帳を登録 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage3Detail {
            get {
                return ResourceManager.GetString("TutorialPage3Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage3Title {
            get {
                return ResourceManager.GetString("TutorialPage3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ddd に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WeekOfDaysFormat {
            get {
                return ResourceManager.GetString("WeekOfDaysFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   総合単語帳は削除できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordbookAlertCannotDelete {
            get {
                return ResourceManager.GetString("WordbookAlertCannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この単語帳を削除しますか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordbookAlertConfirmDelete {
            get {
                return ResourceManager.GetString("WordbookAlertConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全体成績 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordbookCombinedTitle {
            get {
                return ResourceManager.GetString("WordbookCombinedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   説明クイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordbookQuizDescription {
            get {
                return ResourceManager.GetString("WordbookQuizDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単語クイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordbookQuizHead {
            get {
                return ResourceManager.GetString("WordbookQuizHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイトルを入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordbookRenameMessage {
            get {
                return ResourceManager.GetString("WordbookRenameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   説明表示:説明非表示:エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordbookShowDescription {
            get {
                return ResourceManager.GetString("WordbookShowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単語表示:単語非表示:エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordbookShowHead {
            get {
                return ResourceManager.GetString("WordbookShowHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}単語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordbooksToolbarInfoWord {
            get {
                return ResourceManager.GetString("WordbooksToolbarInfoWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordbooksToolbarItemAdd {
            get {
                return ResourceManager.GetString("WordbooksToolbarItemAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   並び替え に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordbooksToolbarItemOrder {
            get {
                return ResourceManager.GetString("WordbooksToolbarItemOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordbookToolbarItemDelete {
            get {
                return ResourceManager.GetString("WordbookToolbarItemDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイトル変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordbookToolbarItemRename {
            get {
                return ResourceManager.GetString("WordbookToolbarItemRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   成績を表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordbookToolbarItemScore {
            get {
                return ResourceManager.GetString("WordbookToolbarItemScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   並び替え に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordbookToolbarItemSort {
            get {
                return ResourceManager.GetString("WordbookToolbarItemSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   注意 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordCaution {
            get {
                return ResourceManager.GetString("WordCaution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   解説 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordCommentary {
            get {
                return ResourceManager.GetString("WordCommentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正解数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordCorrectCount {
            get {
                return ResourceManager.GetString("WordCorrectCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正解率 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordCorrectRate {
            get {
                return ResourceManager.GetString("WordCorrectRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordDelete {
            get {
                return ResourceManager.GetString("WordDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   説明 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordExplanation {
            get {
                return ResourceManager.GetString("WordExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最後のページです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordPageBottomLast {
            get {
                return ResourceManager.GetString("WordPageBottomLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordPageBottomNext {
            get {
                return ResourceManager.GetString("WordPageBottomNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordPageBottomShow {
            get {
                return ResourceManager.GetString("WordPageBottomShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   記憶完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordPageRememberCheck {
            get {
                return ResourceManager.GetString("WordPageRememberCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   weblio検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordPageSearchDictionary {
            get {
                return ResourceManager.GetString("WordPageSearchDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://www.weblio.jp/content/{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordPageSearchDictionaryUrl {
            get {
                return ResourceManager.GetString("WordPageSearchDictionaryUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Google検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordPageSearchGoogle {
            get {
                return ResourceManager.GetString("WordPageSearchGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://www.google.co.jp/search?q={0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordPageSearchGoogleUrl {
            get {
                return ResourceManager.GetString("WordPageSearchGoogleUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wikipedia検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordPageSearchWikipedia {
            get {
                return ResourceManager.GetString("WordPageSearchWikipedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://ja.wikipedia.org/wiki/{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordPageSearchWikipediaUrl {
            get {
                return ResourceManager.GetString("WordPageSearchWikipediaUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   価格 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordPrice {
            get {
                return ResourceManager.GetString("WordPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   QRコード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordQRCode {
            get {
                return ResourceManager.GetString("WordQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordQuiz {
            get {
                return ResourceManager.GetString("WordQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   並び替え に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordSort {
            get {
                return ResourceManager.GetString("WordSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordStore {
            get {
                return ResourceManager.GetString("WordStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   警告 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WordWarning {
            get {
                return ResourceManager.GetString("WordWarning", resourceCulture);
            }
        }
    }
}
