//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// このソース コードは xsd によって自動生成されました。Version=4.6.1055.0 です。
// 
namespace WordbookImpressLibrary.Schemas {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/WordbookImpressApp/blob/master/WordbookImpressApp/Wordb" +
        "ookImpressLibrary/Schemas/WordbookSuggestion.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://github.com/kurema/WordbookImpressApp/blob/master/WordbookImpressApp/Wordb" +
        "ookImpressLibrary/Schemas/WordbookSuggestion.xsd", IsNullable=false)]
    public partial class book {
        
        private string titleField;
        
        private bookImage imageField;
        
        private bookLink[] linkField;
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public bookImage image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("link")]
        public bookLink[] link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/WordbookImpressApp/blob/master/WordbookImpressApp/Wordb" +
        "ookImpressLibrary/Schemas/WordbookSuggestion.xsd")]
    public partial class bookImage {
        
        private string srcField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string src {
            get {
                return this.srcField;
            }
            set {
                this.srcField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/WordbookImpressApp/blob/master/WordbookImpressApp/Wordb" +
        "ookImpressLibrary/Schemas/WordbookSuggestion.xsd")]
    public partial class bookLink {
        
        private string refField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string @ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/WordbookImpressApp/blob/master/WordbookImpressApp/Wordb" +
        "ookImpressLibrary/Schemas/WordbookSuggestion.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://github.com/kurema/WordbookImpressApp/blob/master/WordbookImpressApp/Wordb" +
        "ookImpressLibrary/Schemas/WordbookSuggestion.xsd", IsNullable=false)]
    public partial class wordbooks {
        
        private wordbooksWordbook[] wordbookField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("wordbook")]
        public wordbooksWordbook[] wordbook {
            get {
                return this.wordbookField;
            }
            set {
                this.wordbookField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/WordbookImpressApp/blob/master/WordbookImpressApp/Wordb" +
        "ookImpressLibrary/Schemas/WordbookSuggestion.xsd")]
    public partial class wordbooksWordbook {
        
        private string titleField;
        
        private string refField;
        
        private wordbooksWordbookSources sourcesField;
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string @ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
        
        /// <remarks/>
        public wordbooksWordbookSources sources {
            get {
                return this.sourcesField;
            }
            set {
                this.sourcesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/WordbookImpressApp/blob/master/WordbookImpressApp/Wordb" +
        "ookImpressLibrary/Schemas/WordbookSuggestion.xsd")]
    public partial class wordbooksWordbookSources {
        
        private book[] bookField;
        
        private string[] keywordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("book")]
        public book[] book {
            get {
                return this.bookField;
            }
            set {
                this.bookField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("keyword")]
        public string[] keyword {
            get {
                return this.keywordField;
            }
            set {
                this.keywordField = value;
            }
        }
    }
}
