//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// このソース コードは xsd によって自動生成されました。Version=4.6.1055.0 です。
// 
namespace WordbookImpressLibrary.Schemas.WordbookSuggestion {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/WordbookImpressApp/blob/master/WordbookImpressApp/Wordb" +
        "ookImpressLibrary/Schemas/WordbookSuggestion.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://github.com/kurema/WordbookImpressApp/blob/master/WordbookImpressApp/Wordb" +
        "ookImpressLibrary/Schemas/WordbookSuggestion.xsd", IsNullable=false)]
    public partial class info {
        
        private infoBooks booksField;
        
        private infoSearchword[] searchwordsField;
        
        private infoWordbook[] wordbooksField;
        
        /// <remarks/>
        public infoBooks books {
            get {
                return this.booksField;
            }
            set {
                this.booksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("searchword", IsNullable=false)]
        public infoSearchword[] searchwords {
            get {
                return this.searchwordsField;
            }
            set {
                this.searchwordsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("wordbook", IsNullable=false)]
        public infoWordbook[] wordbooks {
            get {
                return this.wordbooksField;
            }
            set {
                this.wordbooksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/WordbookImpressApp/blob/master/WordbookImpressApp/Wordb" +
        "ookImpressLibrary/Schemas/WordbookSuggestion.xsd")]
    public partial class infoBooks {
        
        private infoBooksBook[] bookField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("book")]
        public infoBooksBook[] book {
            get {
                return this.bookField;
            }
            set {
                this.bookField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/WordbookImpressApp/blob/master/WordbookImpressApp/Wordb" +
        "ookImpressLibrary/Schemas/WordbookSuggestion.xsd")]
    public partial class infoBooksBook {
        
        private string titleField;
        
        private infoBooksBookID[] idsField;
        
        private infoBooksBookImage[] imagesField;
        
        private infoBooksBookLink[] linksField;
        
        private infoBooksBookSpecial specialField;
        
        private string genreField;
        
        private System.DateTime date_pushField;
        
        private bool date_pushFieldSpecified;
        
        private bool obsoleteField;
        
        public infoBooksBook() {
            this.obsoleteField = false;
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("id", IsNullable=false)]
        public infoBooksBookID[] ids {
            get {
                return this.idsField;
            }
            set {
                this.idsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("image", IsNullable=false)]
        public infoBooksBookImage[] images {
            get {
                return this.imagesField;
            }
            set {
                this.imagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("link", IsNullable=false)]
        public infoBooksBookLink[] links {
            get {
                return this.linksField;
            }
            set {
                this.linksField = value;
            }
        }
        
        /// <remarks/>
        public infoBooksBookSpecial special {
            get {
                return this.specialField;
            }
            set {
                this.specialField = value;
            }
        }
        
        /// <remarks/>
        public string genre {
            get {
                return this.genreField;
            }
            set {
                this.genreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime date_push {
            get {
                return this.date_pushField;
            }
            set {
                this.date_pushField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool date_pushSpecified {
            get {
                return this.date_pushFieldSpecified;
            }
            set {
                this.date_pushFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool obsolete {
            get {
                return this.obsoleteField;
            }
            set {
                this.obsoleteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/WordbookImpressApp/blob/master/WordbookImpressApp/Wordb" +
        "ookImpressLibrary/Schemas/WordbookSuggestion.xsd")]
    public partial class infoBooksBookID {
        
        private string typeField;
        
        private string bindingField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string binding {
            get {
                return this.bindingField;
            }
            set {
                this.bindingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/WordbookImpressApp/blob/master/WordbookImpressApp/Wordb" +
        "ookImpressLibrary/Schemas/WordbookSuggestion.xsd")]
    public partial class infoBooksBookImage {
        
        private string srcField;
        
        private infoBooksBookImageSize sizeField;
        
        private bool sizeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string src {
            get {
                return this.srcField;
            }
            set {
                this.srcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public infoBooksBookImageSize size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sizeSpecified {
            get {
                return this.sizeFieldSpecified;
            }
            set {
                this.sizeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/WordbookImpressApp/blob/master/WordbookImpressApp/Wordb" +
        "ookImpressLibrary/Schemas/WordbookSuggestion.xsd")]
    public enum infoBooksBookImageSize {
        
        /// <remarks/>
        large,
        
        /// <remarks/>
        medium,
        
        /// <remarks/>
        small,
        
        /// <remarks/>
        thumbnail,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/WordbookImpressApp/blob/master/WordbookImpressApp/Wordb" +
        "ookImpressLibrary/Schemas/WordbookSuggestion.xsd")]
    public partial class infoBooksBookLink {
        
        private string refField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string @ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/WordbookImpressApp/blob/master/WordbookImpressApp/Wordb" +
        "ookImpressLibrary/Schemas/WordbookSuggestion.xsd")]
    public partial class infoBooksBookSpecial {
        
        private wordbook[] wordbookField;
        
        private object[] ebookField;
        
        private object[] voiceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("wordbook")]
        public wordbook[] wordbook {
            get {
                return this.wordbookField;
            }
            set {
                this.wordbookField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ebook")]
        public object[] ebook {
            get {
                return this.ebookField;
            }
            set {
                this.ebookField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("voice")]
        public object[] voice {
            get {
                return this.voiceField;
            }
            set {
                this.voiceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/WordbookImpressApp/blob/master/WordbookImpressApp/Wordb" +
        "ookImpressLibrary/Schemas/WordbookSuggestion.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://github.com/kurema/WordbookImpressApp/blob/master/WordbookImpressApp/Wordb" +
        "ookImpressLibrary/Schemas/WordbookSuggestion.xsd", IsNullable=false)]
    public partial class wordbook {
        
        private string refField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string @ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/WordbookImpressApp/blob/master/WordbookImpressApp/Wordb" +
        "ookImpressLibrary/Schemas/WordbookSuggestion.xsd")]
    public partial class infoSearchword {
        
        private string[] wordField;
        
        private wordbook[] wordbookField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("word")]
        public string[] word {
            get {
                return this.wordField;
            }
            set {
                this.wordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("wordbook")]
        public wordbook[] wordbook {
            get {
                return this.wordbookField;
            }
            set {
                this.wordbookField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/WordbookImpressApp/blob/master/WordbookImpressApp/Wordb" +
        "ookImpressLibrary/Schemas/WordbookSuggestion.xsd")]
    public partial class infoWordbook {
        
        private string[] titleField;
        
        private string idField;
        
        private infoWordbookAccess accessField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("title")]
        public string[] title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public infoWordbookAccess access {
            get {
                return this.accessField;
            }
            set {
                this.accessField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/WordbookImpressApp/blob/master/WordbookImpressApp/Wordb" +
        "ookImpressLibrary/Schemas/WordbookSuggestion.xsd")]
    public partial class infoWordbookAccess {
        
        private string urlField;
        
        private string idField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
}
